# Generated by Django 4.2.3 on 2023-07-26 04:52

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, help_text='Add your title', max_length=255, null=True)), ('text', wagtail.blocks.TextBlock(blank=True, help_text='Add additional text', null=True))])), ('rich_text', streams.blocks.RichTextBlock()), ('simple_rich_text', streams.blocks.SimpleRichTextBlock()), ('list_display_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('list_blocks', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.CharBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False))])))])), ('call_action_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('internal_page', wagtail.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(default='Learn More', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
