# Generated by Django 4.2.3 on 2023-07-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='custom_title',
            field=models.CharField(help_text='This is blog details Page', max_length=255, null=True),
        ),
    ]
