# Generated by Django 4.2.3 on 2023-07-21 12:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(help_text='Add your title', max_length=255)), ('text', wagtail.blocks.TextBlock(help_text='Add additional text', max_length=255))], blank=True, null=True, use_json_field=True),
        ),
    ]
