# Generated by Django 4.2.3 on 2023-07-24 07:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, help_text='Add your title', max_length=255, null=True)), ('text', wagtail.blocks.TextBlock(blank=True, help_text='Add additional text', max_length=255, null=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
