# Generated by Django 4.2.3 on 2023-07-24 12:23

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0009_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, help_text='Add your title', max_length=255, null=True)), ('text', wagtail.blocks.TextBlock(blank=True, help_text='Add additional text', max_length=255, null=True))])), ('speciality_and_habits', wagtail.blocks.StructBlock([('speciality', wagtail.blocks.CharBlock(blank=True, help_text='Add speciality', max_length=255, null=True)), ('habits', wagtail.blocks.CharBlock(blank=True, help_text='Add habits', max_length=255, null=True))])), ('rich_text', streams.blocks.RichTextBlock()), ('simple_rich_text', streams.blocks.SimpleRichTextBlock()), ('list_display_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('list_blocks', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.CharBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False))])))])), ('call_action_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('internal_page', wagtail.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(default='Learn More', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
