# Generated by Django 4.2.3 on 2023-07-26 04:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0010_alter_flexpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='contact_us',
            field=wagtail.fields.StreamField([('contact_us', wagtail.blocks.StructBlock([('phone', wagtail.blocks.CharBlock(required=True)), ('area', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('our_website', wagtail.blocks.PageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
