# Generated by Django 4.2.3 on 2023-07-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
